name: cypress tests run
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    types: [opened, edited, reopened]

jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Cache node modules
        uses: actions/cache@v2
        id: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: getting project code
        uses: actions/checkout/@v4
      - name: dependencies installation
        run: npm install --force
      - name: running all tests
        run: npm run cy:run:server
      - name: report generation
        run: npm run report:generate
      - name: report uploading
        if: failure() || success()
        uses: actions/upload-artifact@v3
        with:
          name: cypress test run results - mochawesome
          path: cypress/results/mochawesome-merged.html
